# Generated by Django 5.2.6 on 2025-11-01 12:05

import django.core.validators
import django.db.models.deletion
import dottify.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dottify', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='album',
            options={},
        ),
        migrations.AlterUniqueTogether(
            name='album',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='album',
            name='slug',
            field=models.SlugField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='album',
            name='artist_account',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='dottify.dottifyuser'),
        ),
        migrations.AlterField(
            model_name='album',
            name='release_date',
            field=models.DateField(validators=[django.core.validators.MaxValueValidator(limit_value=dottify.models.get_max_release_date)]),
        ),
        migrations.AddConstraint(
            model_name='album',
            constraint=models.UniqueConstraint(fields=('title', 'artist_name', 'format'), name='unique_album_by_artist_and_format'),
        ),
    ]
