# Generated by Django 5.2.6 on 2025-11-01 12:26

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dottify', '0002_alter_album_options_alter_album_unique_together_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Song',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=800)),
                ('length', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(10)])),
                ('position', models.PositiveIntegerField(blank=True, editable=False, null=True)),
                ('album', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tracks', to='dottify.album')),
            ],
            options={
                'ordering': ['album', 'position'],
                'constraints': [models.UniqueConstraint(fields=('title', 'album'), name='unique_song_title_per_album')],
            },
        ),
    ]
