# Generated by Django 5.2.6 on 2025-11-01 12:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dottify', '0003_song'),
    ]

    operations = [
        migrations.CreateModel(
            name='Playlist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('visibility', models.IntegerField(choices=[(0, 'Hidden'), (1, 'Unlisted'), (2, 'Public')], default=0)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='playlists', to='dottify.dottifyuser')),
                ('songs', models.ManyToManyField(related_name='playlists', to='dottify.song')),
            ],
        ),
    ]
