# Generated by Django 5.2.6 on 2025-11-01 12:57

import django.core.validators
import dottify.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dottify', '0004_playlist'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment_text', models.CharField(max_length=800)),
            ],
        ),
        migrations.CreateModel(
            name='Rating',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stars', models.DecimalField(decimal_places=1, max_digits=2, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(5.0), dottify.models.validate_half_step])),
            ],
        ),
    ]
