# Generated by Django 5.2.6 on 2025-11-29 18:03

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dottify', '0006_comment_album_comment_created_at_comment_user_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='album',
            name='retail_price',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=5, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(999.99)]),
        ),
    ]
