# Generated by Django 5.2.6 on 2025-11-29 18:04

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dottify', '0007_alter_album_retail_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='song',
            name='length',
            field=models.PositiveIntegerField(default=0, validators=[django.core.validators.MinValueValidator(10)]),
        ),
    ]
