# Generated by Django 5.2.6 on 2025-11-29 18:11

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dottify', '0008_alter_song_length'),
    ]

    operations = [
        migrations.AlterField(
            model_name='album',
            name='retail_price',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=5, validators=[django.core.validators.MinValueValidator(Decimal('0.00')), django.core.validators.MaxValueValidator(Decimal('999.99'))]),
        ),
    ]
