# Generated by Django 5.2.6 on 2025-12-01 22:20

import django.core.validators
import django.db.models.deletion
import dottify.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dottify', '0011_alter_rating_song_alter_rating_stars'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rating',
            name='stars',
            field=models.DecimalField(decimal_places=1, max_digits=2, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(5.0), dottify.models.validate_half_step]),
        ),
        migrations.AlterField(
            model_name='song',
            name='album',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dottify.album'),
        ),
    ]
